language: c
compiler:
    - clang
    - gcc
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -y gcc-7 libx11-xcb-dev libxcb-randr0-dev libxcb-xinerama0-dev
env:
    - CFLAGS='-DWITH_XINERAMA=1'
script: make
